[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[unified-core]
SigLevel = Optional TrustAll
Server = https://repo.unifiedarch.local/unified-core/$arch

[unified-extra]
SigLevel = Optional TrustAll
Server = https://repo.unifiedarch.local/unified-extra/$arch

[unified-testing]
SigLevel = Optional TrustAll
Server = https://repo.unifiedarch.local/unified-testing/$arch
